-- Crear usuario y tabla para el proyecto CRUD
CREATE USER app_user IDENTIFIED BY app_password;
GRANT CONNECT, RESOURCE TO app_user;

CREATE TABLE app_user.usuarios (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(100) NOT NULL,
  correo VARCHAR2(150) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);
