CREATE USER inv_user IDENTIFIED BY inv_password;
GRANT CONNECT, RESOURCE TO inv_user;

CREATE TABLE inv_user.categorias (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE inv_user.productos (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(150) NOT NULL,
  categoria_id NUMBER,
  stock NUMBER DEFAULT 0,
  precio NUMBER(12,2),
  PRIMARY KEY (id),
  CONSTRAINT fk_categoria FOREIGN KEY (categoria_id) REFERENCES inv_user.categorias(id)
);

CREATE TABLE inv_user.movimientos (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  producto_id NUMBER NOT NULL,
  tipo VARCHAR2(10) NOT NULL,
  cantidad NUMBER NOT NULL,
  fecha TIMESTAMP DEFAULT SYSTIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_mov_prod FOREIGN KEY (producto_id) REFERENCES inv_user.productos(id)
);
